### ISSUE TITLE
hostapplication 里面设置RouteCallback后，无法跳转到plugin页面

### ISSUE THREAD

**Issue by huxiaotian123** [yjfnypeu/Router-RePlugin#1]
RouterConfiguration.get().setCallback(new RouteCallback() {
            @Override
            public void notFound(Uri uri, NotFoundException e) {
                Log.e("route","notFound:-->"+uri.toString());
            }

            @Override
            public void onOpenSuccess(Uri uri, RouteRule rule) {
                Log.e("route","onOpenSuccess:-->"+uri.toString());

            }

            @Override
            public void onOpenFailed(Uri uri, Throwable e) {
                Log.e("route","onOpenFailed:-->"+uri.toString());

            }
        });

hostapplication中设置代码如下，注释掉代码就可以跳转到plugin页面了

replugin 版本2.2.0
ROUTER_VERSION="2.4.5"
PARCELER_VERSION="1.1.4"
UpdatePlugin_version = "2.4.3"
Router_RePlugin_version = "0.4"

**Comment by yjfnypeu** [comment]
设置RouteCallback这里不能直接使用Router提供的方式来设置。需要使用插件或者宿主提供的入口类来进行设置：

- 配置：[HostRouterConfiguration/PluginRouterConfiguration].setRouteCallback(routeCallback)

**Comment by yjfnypeu** [comment]
今天新更新了Wiki文档。常见问题中有对此问题的解释。建议可以去看看。了解更多问题，也更便于使用：

- [常见问题](https://github.com/yjfnypeu/Router-RePlugin/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
