### ISSUE TITLE
是否支持 从plugin 跳转到host 页面？

### ISSUE THREAD

**Issue by huxiaotian123** [yjfnypeu/Router-RePlugin#2]
目前我尝试的结果是 通过   Router.create(url).open(context); host可以跳转到 plugin中，但是 plugin中无法跳转到host。是否plugin中到跳转到代码不一样？

从plugin 中跳转 host 会报错：
E/HostCallbacks: onPluginNotExistsForActivity: Start download... p=bestvhost; i=Intent { flg=0x10000000 cmp=bestvhost/com.lzh.router.replugin.core.RouterBridgeActivity (has extras) }
感觉是replugin 把host 单座插件去加载 然后发现没有这个插件，去下载了

replugin 版本2.2.0
ROUTER_VERSION="2.4.5"
PARCELER_VERSION="1.1.4"
UpdatePlugin_version = "2.4.3"
Router_RePlugin_version = "0.4"

**Comment by yjfnypeu** [comment]
插件-宿主之间是任意跳转的。因为不知道你具体配置是怎样的。具体问题不好定位。配置你可以多参考一下提供的demo。项目下的RePluginDemo文件夹就是。

**Comment by yjfnypeu** [comment]
今天新更新了Wiki文档。常见问题中有对此问题的解释。建议可以去看看。了解更多问题，也更便于使用：

- [常见问题](https://github.com/yjfnypeu/Router-RePlugin/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

**Comment by huxiaotian123** [comment]
排查到现在，发现是我的plugin appliction 里面的 init的host applictionid 写错了。。。。。
豪哥果然牛批啊，天天吹水还这么厉害。。。。
拜服。。。
