### ISSUE TITLE
Replugin加载Facebook问题

### ISSUE THREAD

**Issue by luoshengbo** [yjfnypeu/Router-RePlugin#6]
请问，您当时遇到这个问题是怎么解决的呢，现在很困扰我，Caused by: java.lang.VerifyError: Verifier rejected class com.facebook.AccessTokenManager: com.facebook.AccessTokenManager com.facebook.AccessTokenManager.getInstance() failed to verify

**Comment by yjfnypeu** [comment]
这个没遇到过。看样子是facebook的验证问题。你可以先查查相关资料

**Comment by yjfnypeu** [comment]
我觉得你这问题应该是RePlugin的问题。建议你直接到RePlugin的开源库去问问。
